### ISSUE TITLE
Lil wings not compatible with OneProbe. OneProbe Dev says issue is on your end.

### ISSUE THREAD

**Issue by zachsai** [Toadstool-Studios/Lil-Wings#15] opened 2022-11-25 05:19 UTC
Cannot load game with both installed.
[crash-2022-11-24_19.57.39-fml.txt](https://github.com/McJtyMods/TheOneProbe/files/10087866/crash-2022-11-24_19.57.39-fml.txt)
1.19.2

![image](https://user-images.githubusercontent.com/63996164/203906537-85ecc09d-98ab-4246-adae-68c4ae92e70d.png)

**Comment by CodexAdrian** [comment] 2022-12-10 16:36
Duplicate of #14

**Closed as completed by CodexAdrian** 2022-12-10 16:36 UTC
