### ISSUE TITLE
[1.2.2-fabric] Mod is not compatible with Quilt Loader

### ISSUE THREAD

**Issue by Gronglegrowth** [Toadstool-Studios/Lil-Wings#17] opened 2022-12-08 04:04 UTC
Loaded the game with Quilt 0.17.7, Lil Wings 1.2.2, and its deps, and am met with [this crash](https://mclo.gs/qlS0wVf).

**Comment by CodexAdrian** [comment] 2022-12-10 16:35
Duplicate of #11

**Closed as completed by CodexAdrian** 2022-12-10 16:35 UTC
